# Generated by Django 3.2.12 on 2022-04-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('profile_image_link', models.TextField(max_length=800)),
                ('preview', models.BooleanField(default=False)),
            ],
        ),
    ]
