# Generated by Django 3.2.12 on 2022-04-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=200)),
                ('show', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='home',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='home',
            name='profile_image_link',
            field=models.CharField(max_length=800),
        ),
    ]
