# Generated by Django 3.2.12 on 2022-04-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_link_color_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=500)),
                ('image_link', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
