# Generated by Django 3.2.12 on 2022-04-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_project_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='favicon',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='link',
            name='shadow_color_code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
