# Generated by Django 3.2.12 on 2022-04-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220427_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='bio_data',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='link',
            name='text_color_code',
            field=models.CharField(default='#fffff', max_length=50),
        ),
    ]
