# Generated by Django 3.2.12 on 2022-04-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_link_text_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='logo_link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='home',
            name='shortuct_icon_link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
